FROM ubuntu:18.04 

RUN apt-get update --fix-missing && \
    apt-get install -y wget bzip2 ca-certificates curl git \
    software-properties-common apt-transport-https \
    build-essential libssl-dev net-tools telnet vim

RUN 